name: Render Rmd to PDF

on:
  push:
    branches: [main] # This means it will only run on pushes to the "main" branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check file existence in main repo
      run: |
        pwd
        ls -alh 3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'
    
    # Setup caching for R packages and TinyTeX installation
    - name: Setup R Package Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.R/library
          ~/.TinyTeX
          ~/AppData/Roaming/TinyTeX
          /Library/TinyTeX
          /usr/local/opt/tinytex/bin
          /usr/share/tinytex/bin
        key: ${{ runner.OS }}-r-${{ hashFiles('DESCRIPTION') }}
    
    # Install CRAN packages
    - name: Install CRAN dependencies
      run: |
        Rscript -e "install.packages(c('readr', 'tidyr', 'gridExtra', 'reshape2', 'viridis', 'EnhancedVolcano', 'rmarkdown', 'tinytex', 'knitr', 'remotes'))"
        Rscript -e "remotes::install_version('ggplot2', version='3.3.6')"

        Rscript -e "install.packages('XML', repos = 'http://cran.r-project.org')"

    # Install Bioconductor packages
    - name: Install Bioconductor dependencies
      run: |
        Rscript -e "install.packages('BiocManager', repos = 'http://cran.r-project.org')"
        Rscript -e "BiocManager::install('DESeq2')"
        Rscript -e "BiocManager::install('biomaRt')"
        Rscript -e "BiocManager::install('genefilter')"
        Rscript -e "BiocManager::install('org.Hs.eg.db')"
        Rscript -e "BiocManager::install('clusterProfiler')"
        Rscript -e "BiocManager::install('ggtree')"
        Rscript -e "if ('genefilter' %in% installed.packages()[,'Package']) { print('genefilter installed successfully') } else { stop('genefilter not installed') }"

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Render Rmd file
      run: |
        cd 3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots
        Rscript -e "rmarkdown::render('Rmd_RNAseq_Multiple_Volcano_Plots_Comparison.Rmd', output_format = 'pdf_document', output_dir = 'Outputs', params = list(data_path = 'countMatrix.tsv', meta_path = 'metadata.tsv'))"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add 3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Outputs/*
        git commit -m "Add rendered PDF" || echo "No changes to commit"
        git push
