name: Render Rmd to PDF

on:
  push:
    branches: [main] # This means it will only run on pushes to the "main" branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check file existence in main repo
      run: |
        pwd
        ls -alh 3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install system dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install CRAN packages
      run: |
        Rscript -e "install.packages(c('readr', 'tidyr', 'gridExtra', 'reshape2', 'viridis', 'rmarkdown', 'tinytex', 'knitr', 'remotes', 'curl', 'httr', 'devtools', 'BiocManager'))"
        Rscript -e "remotes::install_version('ggplot2', version='3.3.6')"

    - name: Install Bioconductor packages
      run: |
        Rscript -e "BiocManager::install(c('GenomeInfoDb', 'Biostrings', 'KEGGREST', 'AnnotationDbi', 'DO.db', 'DESeq2', 'biomaRt', 'org.Hs.eg.db', 'ComplexHeatmap', 'genefilter', 'ggtree', 'EnhancedVolcano', 'clusterProfiler'))"

    - name: Install TinyTeX for rendering R Markdown to PDF
      run: |
        Rscript -e "tinytex::install_tinytex()"
        Rscript -e "lualatex_path <- Sys.which('lualatex'); writeLines(paste('PATH=', dirname(lualatex_path), sep=''), con = '~/.Renviron')"

    - name: Verify Package Installation
      run: |
        intended_packages <- c('readr', 'tidyr', 'gridExtra', 'reshape2', 'viridis', 'EnhancedVolcano', 'rmarkdown', 'tinytex', 'knitr', 'remotes', 'curl', 'httr', 'devtools', 'ggplot2', 'GenomeInfoDb', 'Biostrings', 'KEGGREST', 'AnnotationDbi', 'DO.db', 'DESeq2', 'biomaRt', 'org.Hs.eg.db', 'ComplexHeatmap', 'clusterProfiler', 'ggtree', 'genefilter')
        installed_packages <- installed.packages()[, "Package"]
        missing_packages <- setdiff(intended_packages, installed_packages)
        if (length(missing_packages) > 0) {
          cat("These packages failed to install:\n")
          print(missing_packages)
        } else {
          cat("All packages installed successfully!\n")
        }
      shell: Rscript {0}
      if: always()

    - name: Render Rmd file
      run: |
        cd 3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots
        Rscript -e "rmarkdown::render('Rmd_RNAseq_Multiple_Volcano_Plots_Comparison.Rmd', output_format = 'pdf_document', output_dir = 'Outputs', params = list(data_path = 'countMatrix.tsv', meta_path = 'metadata.tsv'))"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add 3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Outputs/*
        git commit -m "Add rendered PDF" || echo "No changes to commit"
        git push
