name: Render Rmd to PDF

on:
  push:
    branches: [main] # Run only on pushes to the "main" branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Checkout confidential files
      uses: actions/checkout@v2
      with:
        repository: MohammadRezaMohajeri/confidential_files
        token: ${{ secrets.GIT_PAT }}
        path: ./confidential_files

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install R dependencies
      run: |
        install_cmds <- c(
          "install.packages(c('rmarkdown', 'tinytex'))",
          "tinytex::install_tinytex()",
          "lualatex_path <- Sys.which('lualatex'); writeLines(paste('PATH=', dirname(lualatex_path), sep=''), con = '~/.Renviron')"
        )
        sapply(install_cmds, function(cmd) system(paste('Rscript -e', shQuote(cmd))))

    - name: Render Rmd file
      run: |
        Rscript -e "rmarkdown::render('3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Rmd_RNAseq_Multiple_Volcano_Plots_Comparison.Rmd', output_format = 'pdf_document', output_dir = '3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Outputs', params = list(data_path = './confidential_files/Clari_Seond_Task_CountMetadata/countMatrix.tsv', meta_path = './confidential_files/Clari_Seond_Task_CountMetadata/metadata.tsv'))"
