name: Render R Markdown Document

on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the main repo
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 

    # Step 2: Checkout the confidential_files repository
    - name: Checkout private repository with confidential files
      uses: actions/checkout@v2
      with:
        repository: MohammadRezaMohajeri/confidential_files
        token: ${{ secrets.GIT_PAT }}
        path: ./confidential_files

    # Step 3: Set up R and necessary system dependencies
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'  # Modify this to your desired R version if necessary
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc libcurl4-openssl-dev libssl-dev libxml2-dev  # Adding some typical system dependencies for R packages
    
    # Step 4: Install R dependencies. (This can be trimmed down further if you know exactly which packages you need)
    - name: Install dependencies
      run: |
        install.packages(c("rmarkdown", "tidyverse", "ggplot2"))  # Add or remove packages based on your requirements

    # Step 5: Render the R Markdown file
    - name: Render Rmd file
      run: |
        Rscript -e "rmarkdown::render('3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Rmd_RNAseq_Multiple_Volcano_Plots_Comparison.Rmd', output_format = 'pdf_document', output_dir = '3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Outputs', params = list(data_path = './confidential_files/Clari_Seond_Task_CountMetadata/countMatrix.tsv', meta_path = './confidential_files/Clari_Seond_Task_CountMetadata/metadata.tsv'))"
