name: Render Rmd to PDF

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Checkout private repository with confidential files
      uses: actions/checkout@v2
      with:
        repository: MohammadRezaMohajeri/confidential_files
        token: ${{ secrets.GIT_PAT }}
        path: ./confidential_files
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'

    # Only installing rmarkdown as it's the minimum requirement for this test
    - name: Install rmarkdown
      run: |
        Rscript -e "install.packages('rmarkdown')"

    # This step will list all the directories and files in the root
    - name: List directories
      run: |
        ls -alh

    - name: Render Rmd file
      run: |
        Rscript -e "rmarkdown::render('3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Rmd_RNAseq_Multiple_Volcano_Plots_Comparison.Rmd', output_format = 'pdf_document', output_dir = '3.RNA_Seq_Analysis/RNA_Seq_Plots/Volcano_Plots/Outputs', params = list(data_path = '../confidential_files/Clari_Seond_Task_CountMetadata/countMatrix.tsv', meta_path = '../confidential_files/Clari_Seond_Task_CountMetadata/metadata.tsv'))"
